### ISSUE TITLE
Mistakes of v1.0.1 source codes in released page

### ISSUE THREAD

**Issue by qcxia20** [paiardin/DockingPie#1]
I've used source codes from released page to install DockingPie plugin. And when I try to install packages with "configure" button. A 404 error was reported since that the given link is not correct. 
This issue is just to remind somebody like me who tried that copy of source codes and got this error.
If the developers can notice this issue and updated a newer version of released source codes, it will be much better.

The error comes from a small mistake in the codes below.
The codes of the latest commit in branch "main", which is the same in the [source codes](https://github.com/paiardin/DockingPie/archive/refs/heads/main.zip) from [user guide](https://github.com/paiardin/DockingPie/wiki/User's-Guide)

https://github.com/paiardin/DockingPie/blob/e7bacf40ad93e9e744cf8d09c6c1df8b927ced8e/DockingPie1/lib/docking_program_main/docking_program_gui/frames.py#L423-L431
While the codes from released source codes is correct, as follows,
```python
    def configure_external_tools_directory(self):

        if sys.platform == "linux":
            dir_link = "https://github.com/paiardin/DockingPie/releases/download/Files_v1.0.0/external_tools_linux.zip"
            dir_name = "external_tools_linux"
        if sys.platform == "darwin":
            dir_link = "https://github.com/paiardin/DockingPie/releases/download/Files_v1.0.0/external_tools_macOS.zip"
            dir_name = "external_tools_macOS"
        if sys.platform == "win32":
            dir_link = "https://github.com/paiardin/DockingPie/releases/download/Files_v1.0.0/external_tools_windows.zip"
            dir_name = "external_tools_windows"
```
The solution of this 404 error is simple, i.e., just to modify the codes and restart PyMol.

**Comment by SerenaRosi** [comment]
Dear qcxia20,
thank you for your interest in DockingPie.

Some minor changes may occur after the source code has been released.
**To be always up to date**, we strongly suggest to refer to the main GitHub page (https://github.com/paiardin/DockingPie) or to the source code provided in the DockingPie Utilities (https://github.com/paiardin/DockingPie/releases/download/versioning/DockingPie1.zip)

Best Regards, 
DockingPie Developers
