### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by Tangbbmc** [paiardin/DockingPie#2]
I like this plugin (DockingPie) very much. However, recently, I run vina program via this plugin, PyMOL always reported the following issue. Could you help me to deal with it? Thank you!

File "d:\anaconda\lib\site-packages\pmg_tk\startup\DockingPie1\lib\docking_program_main\Functions\dockings_thread.py", line 396, in on_update_results_tab
    self.tab.results_frame = ResultsFrame(parent=self.tab,
  File "d:\anaconda\lib\site-packages\pmg_tk\startup\DockingPie1\lib\docking_program_main\docking_program_gui\frames.py", line 1019, in __init__
    if Path(self.log_file).is_file():
  File "d:\anaconda\lib\pathlib.py", line 1038, in __new__
    self = cls._from_parts(args, init=False)
  File "d:\anaconda\lib\pathlib.py", line 679, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "d:\anaconda\lib\pathlib.py", line 663, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by SerenaRosi** [comment]
Dear Tangbbmc,
thank you for your interest in DockingPie. 

Please notice commit 59c9a02 (6th February 2023) that should have solved this issue. 
If you think your DockingPie version is up to date and you are still facing this issue, please contact us again with more information about the DockingPie source-code in use and/or about the system analyzed with Vina. 

Best,
Serena

**Comment by Tangbbmc** [comment]
Dear Serena,
 Thank you very much for your reply! I have made corresponding change for vina_functions.py script based on the information you provided (1 addition and 4 deletions). The issue mentioned previously did not appear. But the running result of Vina program only returned a summary of docking parameters (see below). No docking poses and scores.

 Summary:
Exhaustiveness: 40
Energy Range: 5
Ligand: 01_ATP_Vina
Receptor: 02_apo_Vina
Cavity: Grid Center_4

发件人：Serena Rosignoli ***@***.***>
发送日期：2023-03-13 15:37:23
收件人：paiardin/DockingPie ***@***.***>
抄送人：Tangbbmc ***@***.***>,Author ***@***.***>
主题：Re: [paiardin/DockingPie] TypeError: expected str, bytes or os.PathLike object, not NoneType (Issue #2)

Dear Tangbbmc,
 thank you for your interest in DockingPie.
Please notice commit 59c9a02 (6th February 2023) that should have solved this issue.
 If you think your DockingPie version is up to date and you are still facing this issue, please contact us again with more information about the DockingPie source-code in use and/or about the system analyzed with Vina.
Best,
 Serena

**Comment by SerenaRosi** [comment]
The are more modifications than the one I pointed the focus on. I would suggest to download the plugin from its main branch and re-install it. However, here there is something going wrong with your docking simulation, it may be related to the ligand/receptor/parameters setup.

**Comment by Tangbbmc** [comment]
OK. Thank you for your suggestion.



唐王刚 Wanggang Tang
博士 副教授 
Ph.D.  Associate Professor
Organization: Bengbu Medical College
Address: No. 2600, Donghai Avenue. Bengbu, Anhui, China






  



---- Replied Message ----
From  Serena ***@***.***> Date  03/13/2023 17:09 To  ***@***.***> Cc  ***@***.***>***@***.***> Subject  Re: [paiardin/DockingPie] TypeError: expected str, bytes or os.PathLike object, not NoneType (Issue #2)  

The are more modifications than the one I pointed the focus on. I would suggest to download the plugin from its main branch and re-install it. However, here there is something going wrong with your docking simulation, it may be related to the ligand/receptor/parameters setup.
