### ISSUE TITLE
Any way to manually define ligands/receptors?

### ISSUE THREAD

**Issue by polowish** [paiardin/DockingPie#3]
Plug-in automatically detects ligands and receptors. The ligand (peptide) I'm attempting to use is recognized as a receptor and I'm therefore unable to dock with it. Is there any way around this?

**Comment by samcphee** [comment]
I am also interested in the answer to this.

**Comment by SerenaRosi** [comment]
Hi! Thank you for your interest in DockingPie and sorry for the late reply. 

At the moment, it is not possible to manually define ligands/receptor. It is one of the new features that will be implemented in the next release of our plugin. 

Best,
Serena
