### ISSUE TITLE
generate ligand is seemingly busted for me, please help resolve asap

### ISSUE THREAD

**Issue by jhh1492** [paiardin/DockingPie#5]
PyMOL>fetch 7roq
TITLE     Alternative Structure of Human ABCA1
 ExecutiveLoad-Detail: Detected mmCIF
 CmdLoad: "./7roq.cif" loaded as "7roq".
 CmdLoad: "/home/scientist/Downloads/Conformer3D_COMPOUND_CID_4912-2.sdf" loaded as "Conformer3D_COMPOUND_CID_4912-2".
 Executive: object "temp_obj" created.
 Executive: object temp_obj created.
Traceback (most recent call last):
  File "/home/scientist/.pymol/startup/DockingPie1/lib/docking_program_main/docking_program_gui/tabs.py", line 2188, in generate_ligand_func
    is_receptor = False)
  File "/home/scientist/.pymol/startup/DockingPie1/lib/docking_program_main/Functions/general_docking_func.py", line 284, in __init__
    self.generate_receptor()
  File "/home/scientist/.pymol/startup/DockingPie1/lib/docking_program_main/Functions/general_docking_func.py", line 306, in generate_receptor
    self.generate_checked_object()
  File "/home/scientist/.pymol/startup/DockingPie1/lib/docking_program_main/Functions/general_docking_func.py", line 412, in generate_checked_object
    os.rename(old_name, new_name)
FileNotFoundError: [Errno 2] No such file or directory: 'Conformer3D_COMPOUND_CID_4912-2.pdbqt' -> '01_Conformer3D-COMPOUND-CID-4912-2_Vina.pdbqt'
INFO and CONTACTS
Copyright (C): 2022 Serena Rosignoli, Alessandro Paiardini
Contacts: serena.rosignoli@uniroma1.it, alessandro.paiardini@uniroma1.it
For information on DockingPie 1.0 visit:
https://github.com/paiardin/DockingPie

# DockingPie
- Version: 1.2.1
- Plugin path: /home/scientist/.pymol/startup/DockingPie1/lib/docking_program_main 
- Config directory: /home/scientist/.pymol/startup/DockingPie1/lib/docking_program_main/config

# PyMOL
- Version: 2.5.2
- Path: /home/scientist/pymol/bin/python
- Qt: PyQt5
- Has Conda: True

# Python
- Version: 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) 
[GCC 9.3.0]
- Arch: 64
- Path: /home/scientist/pymol/bin/python

# Operating system
- Platform: linux
- Arch: 64

# Python libs
- PyQt5: 5.12.3
- Conda version: 4.10.3
- Numpy version: 1.21.2
- Biopython version: 1.79

**Comment by SerenaRosi** [comment]
Please double-check that everything is properly configured in DockingPie. 
Section 3 in User's guide.


Best, 
Serena

**Comment by jhh1492** [comment]
Traceback (most recent call last):
  File "/home/scientist/pymol/DockingPie1/lib/docking_program_main/config/prepare_ligand4.py", line 236, in <module>
    attach_singletons=attach_singletons)
  File "/home/scientist/pymol/DockingPie1/lib/docking_program_main/config/AutoDockTools/AutoDockTools/MoleculePreparation.py", line 1032, in __init__
    detect_bonds_between_cycles=detect_bonds_between_cycles)
  File "/home/scientist/pymol/DockingPie1/lib/docking_program_main/config/AutoDockTools/AutoDockTools/MoleculePreparation.py", line 803, in __init__
    self.aromCs = self.ACM.setAromaticCarbons(molecule)
  File "/home/scientist/pymol/DockingPie1/lib/docking_program_main/config/AutoDockTools/AutoDockTools/atomTypeTools.py", line 225, in setAromaticCarbons
    assert len(molecule.allAtoms.bonds[0])
AssertionError
Traceback (most recent call last):
  File "/home/scientist/pymol/DockingPie1/lib/docking_program_main/docking_program_gui/tabs.py", line 2206, in generate_ligand_func
    is_receptor = False)
  File "/home/scientist/pymol/DockingPie1/lib/docking_program_main/Functions/general_docking_func.py", line 284, in __init__
    self.generate_receptor()
  File "/home/scientist/pymol/DockingPie1/lib/docking_program_main/Functions/general_docking_func.py", line 306, in generate_receptor
    self.generate_checked_object()
  File "/home/scientist/pymol/DockingPie1/lib/docking_program_main/Functions/general_docking_func.py", line 412, in generate_checked_object
    os.rename(old_name, new_name)
FileNotFoundError: [Errno 2] No such file or directory: 'Conformer3D_COMPOUND_CID_4912-2.pdbqt' -> '01_Conformer3D-COMPOUND-CID-4912-2_Smina.pdbqt'

uninstalled plugin and reinstalled it, still issues whenever using generet receptor or genereate ligand??

**Comment by jhh1492** [comment]
# DockingPie
- Version: 1.2.1
- Plugin path: /home/scientist/pymol/DockingPie1/lib/docking_program_main 
- Config directory: /home/scientist/pymol/DockingPie1/lib/docking_program_main/config

# PyMOL
- Version: 2.5.0
- Path: /home/scientist/pymol/bin/python
- Qt: PyQt5
- Has Conda: True

# Python
- Version: 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) 
[GCC 9.3.0]
- Arch: 64
- Path: /home/scientist/pymol/bin/python

# Operating system
- Platform: linux
- Arch: 64

# Python libs
- PyQt5: 5.12.3
- Conda version: 4.10.1
- Numpy version: 1.20.2
- Biopython version: 1.78

**Comment by jhh1492** [comment]
Python installed, please wait for the rest of ADFRsuite to be installed
**./install.sh: 1: /home/scientist/pymol/DockingPie1/lib/docking_program_main/config/external_tools_linux/ADFRsuite_x86_64Linux_1.0/Tools/archosv: Permission denied**
Running /home/scientist/pymol/DockingPie1/lib/docking_program_main/config/external_tools_linux/ADFRsuite_x86_64Linux_1.0/bin/python2.7 Tools/install.py  
Installing  ADSPackages
Installing files from CCSBpckgs .tar.gz
Installing files from ThirdPartyPacks .tar.gz
Creating scripts
current directory: /home/scientist/pymol/DockingPie1/lib/docking_program_main/config/external_tools_linux/ADFRsuite_x86_64Linux_1.0

**Comment by jhh1492** [comment]
could this be causing all of these issues? why would adfr not installing affect all others? whats best bet for fixing? this occurs every time i uninstall and redownload, can't do a sudo command because it's already installed each time I opened plugin

**Comment by jhh1492** [comment]
I downloaded a new conda, installed pymol 3.0, and reinstalled the application and it is still giving this error, the recptor seemingly does fine, the ligan it loads it as "temp object" that is missing many atoms, when i hit generate i get below File "/home/scientist/anaconda3/envs/pymol/lib/python3.11/site-packages/pmg_tk/startup/DockingPie1/lib/docking_program_main/Functions/general_docking_func.py", line 412, in generate_checked_object
    os.rename(old_name, new_name)
FileNotFoundError: [Errno 2] No such file or directory: 'Probucol.pdbqt' -> '02_Probucol_Vina.pdbqt'

again new conda, new pymol, new everything to try and get this plug in to work...

**Comment by SerenaRosi** [comment]
I believe that you are pointing different type of errors. 

- This error, as already said, is related to the fact that you did not properly configured DockingPie. 

    See **Section 3 in User's guide**: 
    https://github.com/paiardin/DockingPie/releases/download/versioning/DockingPie_User_Guide.pdf

    _File "/home/scientist/anaconda3/envs/pymol/lib/python3.11/site-packages/pmg_tk/startup/DockingPie1/lib/docking_program_main/Functions/general_docking_func.py", line 412, in generate_checked_object
    os.rename(old_name, new_name)
    FileNotFoundError: [Errno 2] No such file or directory: 'Probucol.pdbqt' -> '02_Probucol_Vina.pdbqt'_

- The reason for the missing atoms in the ligand is a known issue that we are still trying to point out. 

More over, DockingPie has not been tested for PyMOL 3.0 yet, keeping downloading and re-installing won't solve any issue.

**Comment by jhh1492** [comment]
I am not uninstalling and reinstalling the same thing. I have tried multiple versions and always that same installation error from yalls autoadd button. I have tried open source 2.4,2.5 and incentive 2.4 (multiple versions tried) ,2.5.2 and more, so have tested ones listed as approved/tested by you guys. Every single time I get this error (see below). I am following you instructions to the tee for both incentive and open-source. 

(inpymol) scientist@OptiPlex-9020:~$ ./install.sh: 1: /home/scientist/anaconda3/envs/openpie/lib/python3.11/site-packages/pmg_tk/startup/DockingPie1/lib/docking_program_main/config/external_tools_linux/ADFRsuite_x86_64Linux_1.0/Tools/archosv: Permission denied

If you would like, to prove this is not user error, I will download whichever incentive and open source pymol version you prefer, screen record the installation process, and send your way.

**Comment by SerenaRosi** [comment]
Please provide a screen of the CONFIGURATION tab.

**Comment by SerenaRosi** [comment]
Please, send a screenshot of the CONFIGURATION tab.

**Comment by jhh1492** [comment]
[Bb.zip](https://github.com/paiardin/DockingPie/files/14706805/Bb.zip)

**Comment by jhh1492** [comment]
![IMG_5408](https://github.com/paiardin/DockingPie/assets/154352089/6fb2d87d-7607-4a33-815c-a82e9c7aff99)
![IMG_5407](https://github.com/paiardin/DockingPie/assets/154352089/189f2778-3f3e-4d89-bd6d-4b55a8d06eb1)

**Comment by jhh1492** [comment]
That is what happens for all versions, says everything got downloaded fine from the plugin, only in one line of terminal output do you see the perms denied

**Comment by jhh1492** [comment]
mabe the channel priority from conda messes it up? or ADFR license is up? no clue just trying to help in anyway possible

**Comment by SerenaRosi** [comment]
We have recently become aware of unexpected issues reported by multiple users, which we believe may be stemming from recent updates to PyMOL and/or other external libraries. These issues were not encountered previously and are likely a result of incompatibilities introduced by these updates. As a result, we have temporarily placed DockingPie under maintenance mode while we work diligently to resolve these issues. Once these issues are resolved, we will promptly update our GitHub page to inform users of the fixes and any necessary instructions. Thank you for your understanding and cooperation during this period.

Best, 
Serena

**Comment by jhh1492** [comment]
No worries this stuff in tough in general, implementing pymol and conda for our ease only complicates things. If you want an external Beta tester let me know, can test any version of either main dependency. Appreciative of yalls hard work! All the best

**Comment by paiardin** [comment]
Hi, we have just released an updated version of [DockingPie](https://github.com/paiardin/DockingPie/archive/refs/heads/main.zip), which should fix this issue. Let us know!
